from pathlib import Path

root = Path(r'c:/laragon/www/buku-induk')

# Patch helper

def patch(path, old, new, desc):
    text = path.read_text(encoding='utf-8')
    if old not in text:
        raise RuntimeError(f'OLD block not found for {desc} in {path}')
    path.write_text(text.replace(old, new), encoding='utf-8')
    print(f'Patched {desc}')

# edit.blade.php
edit_path = root / 'resources' / 'views' / 'tu' / 'buku-induk' / 'edit.blade.php'
old_edit = """                        {{-- PREVIEW FOTO --}}
                        <div class=\"foto-placeholder\" id=\"fotoPlaceholder\" style=\"display: {{ isset($siswa->user) && isset($siswa->user->photo) && $siswa->user->photo ? 'none' : 'flex' }};\">\n                            <i class=\"fas fa-user-graduate\"></i>\n                        </div>\n                        @php\n                            $initialPhoto = isset($siswa->user) && isset($siswa->user->photo) && $siswa->user->photo ? $siswa->user->photo : null;\n                            $initialPhotoPath = $initialPhoto ? (strpos($initialPhoto, 'foto-siswa/') === 0 ? $initialPhoto : 'foto-siswa/' . basename($initialPhoto)) : null;\n                        @endphp\n                        <img src=\"{{ $initialPhotoPath ? asset('storage/' . $initialPhotoPath) : '' }}\" alt=\"{{ $siswa->nama_lengkap }}\" class=\"foto-preview\" id=\"fotoPreview\" style=\"display: {{ $initialPhotoPath ? 'block' : 'none' }};\">"""
new_edit = """                        {{-- PREVIEW FOTO --}}\n                        @php\n                            $initialPhoto = $siswa->foto ?: (isset($siswa->user) ? $siswa->user->photo : null);\n                            $initialPhotoPath = $initialPhoto ? (strpos($initialPhoto, 'foto-siswa/') === 0 ? $initialPhoto : 'foto-siswa/' . basename($initialPhoto)) : null;\n                        @endphp\n                        <div class=\"foto-placeholder\" id=\"fotoPlaceholder\" style=\"display: {{ $initialPhotoPath ? 'none' : 'flex' }};\">\n                            <i class=\"fas fa-user-graduate\"></i>\n                        </div>\n                        <img src=\"{{ $initialPhotoPath ? asset('storage/' . $initialPhotoPath) : '' }}\" alt=\"{{ $siswa->nama_lengkap }}\" class=\"foto-preview\" id=\"fotoPreview\" style=\"display: {{ $initialPhotoPath ? 'block' : 'none' }};\">"""
patch(edit_path, old_edit, new_edit, 'edit preview block')

old_edit_btn = """                            <button type=\"button\" class=\"btn-remove-foto\" id=\"btnRemoveFoto\" style=\"display: {{ isset($siswa->user) && isset($siswa->user->photo) && $siswa->user->photo ? 'inline-flex' : 'none' }};\">\n                                <i class=\"fas fa-trash\"></i> Hapus Foto\n                            </button>"""
new_edit_btn = """                            <button type=\"button\" class=\"btn-remove-foto\" id=\"btnRemoveFoto\" style=\"display: {{ $initialPhotoPath ? 'inline-flex' : 'none' }};\">\n                                <i class=\"fas fa-trash\"></i> Hapus Foto\n                            </button>"""
patch(edit_path, old_edit_btn, new_edit_btn, 'edit remove button')

# show.blade.php
show_path = root / 'resources' / 'views' / 'tu' / 'buku-induk' / 'show.blade.php'
old_show = """                            @php\n                                $photoPath = $siswa->user->photo ?? null;\n                                $storagePhoto = null;\n                                if ($photoPath) {\n                                    $storagePhoto = strpos($photoPath, 'foto-siswa/') === 0 ? $photoPath : 'foto-siswa/' . basename($photoPath);\n                                }\n                            @endphp"""
new_show = """                            @php\n                                $photoPath = $siswa->foto ?: ($siswa->user->photo ?? null);\n                                $storagePhoto = null;\n                                if ($photoPath) {\n                                    $storagePhoto = strpos($photoPath, 'foto-siswa/') === 0 ? $photoPath : 'foto-siswa/' . basename($photoPath);\n                                }\n                            @endphp"""
patch(show_path, old_show, new_show, 'show photo source')

# controller
controller_path = root / 'app' / 'Http' / 'Controllers' / 'TU' / 'BukuIndukController.php'
old_ctrl_update = """        $validated = $request->validate([\n            'nis' => 'required|string',\n            'nama_lengkap' => 'required|string',\n            'nisn' => 'nullable|string',\n            'jenis_kelamin' => 'nullable|string',\n            'tempat_lahir' => 'nullable|string',\n            'tanggal_lahir' => 'nullable|date',\n            'agama' => 'nullable|string',\n            'kewarganegaraan' => 'nullable|string',\n            'dusun' => 'nullable|string',\n            'kelurahan' => 'nullable|string',\n            'kecamatan' => 'nullable|string',\n            'rt' => 'nullable|string',\n            'rw' => 'nullable|string',\n            'kode_pos' => 'nullable|string',\n            'foto' => 'nullable|image|mimes:jpeg,png,jpg,webp|max:2048',\n            // other fields may be added as needed\n        ]);\n\n        // Update main siswa fields\n        $siswa->update($validated);\n"""
new_ctrl_update = """        $validated = $request->validate([\n            'nis' => 'required|string',\n            'nama_lengkap' => 'required|string',\n            'nisn' => 'nullable|string',\n            'jenis_kelamin' => 'nullable|string',\n            'tempat_lahir' => 'nullable|string',\n            'tanggal_lahir' => 'nullable|date',\n            'agama' => 'nullable|string',\n            'kewarganegaraan' => 'nullable|string',\n            'dusun' => 'nullable|string',\n            'kelurahan' => 'nullable|string',\n            'kecamatan' => 'nullable|string',\n            'rt' => 'nullable|string',\n            'rw' => 'nullable|string',\n            'kode_pos' => 'nullable|string',\n            'foto' => 'nullable|image|mimes:jpeg,png,jpg,webp|max:2048',\n            // other fields may be added as needed\n        ]);\n\n        $siswaData = $validated;\n        unset($siswaData['foto']);\n\n        // Update main siswa fields\n        $siswa->update($siswaData);\n"""
patch(controller_path, old_ctrl_update, new_ctrl_update, 'controller update foto handling')

old_ctrl_photo = """        // Handle photo upload / removal for related user\n        $removeFoto = $request->input('remove_foto', '0');\n        if ($removeFoto === '1' && $siswa->user && $siswa->user->photo) {\n            Storage::disk('public')->delete($siswa->user->photo);\n            $siswa->user->photo = null;\n            $siswa->user->save();\n        }\n\n        if ($request->hasFile('foto')) {\n            $file = $request->file('foto');\n            $path = $file->store('foto-siswa', 'public');\n            if ($siswa->user) {\n                if ($siswa->user->photo) {\n                    Storage::disk('public')->delete($siswa->user->photo);\n                }\n                $siswa->user->photo = $path;\n                $siswa->user->save();\n            }\n        }\n\n        $siswa->save();\n"""
new_ctrl_photo = """        // Handle photo upload / removal for siswa\n        $removeFoto = $request->input('remove_foto', '0');\n        if ($removeFoto === '1') {\n            if ($siswa->foto && Storage::disk('public')->exists($siswa->foto)) {\n                Storage::disk('public')->delete($siswa->foto);\n            }\n            $oldFotoPath = $siswa->foto;\n            $siswa->foto = null;\n            if ($siswa->user && $siswa->user->photo && $siswa->user->photo === $oldFotoPath) {\n                Storage::disk('public')->delete($siswa->user->photo);\n                $siswa->user->photo = null;\n                $siswa->user->save();\n            }\n        }\n\n        if ($request->hasFile('foto')) {\n            if ($siswa->foto && Storage::disk('public')->exists($siswa->foto)) {\n                Storage::disk('public')->delete($siswa->foto);\n            }\n            $file = $request->file('foto');\n            $path = $file->store('foto-siswa', 'public');\n            $siswa->foto = $path;\n            if ($siswa->user) {\n                if ($siswa->user->photo && $siswa->user->photo !== $path && Storage::disk('public')->exists($siswa->user->photo)) {\n                    Storage::disk('public')->delete($siswa->user->photo);\n                }\n                $siswa->user->photo = $path;\n                $siswa->user->save();\n            }\n        }\n\n        $siswa->save();\n"""
patch(controller_path, old_ctrl_photo, new_ctrl_photo, 'controller photo upload/remove')

print('All patches complete.')
